name: photoprism
description: An app for photoprism.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

publish_to: none

dependencies:
  background_fetch: ^0.7.1
  cached_network_image: ^3.0.0-nullsafety
  connectivity: ^3.0.2
  crypto: ^3.0.0
  cupertino_icons: ^1.0.0
  device_info: ^2.0.0
  drag_select_grid_view: ^0.3.1
  draggable_scrollbar:
    git:
      url: git://github.com/thielepaul/flutter-draggable-scrollbar.git
  easy_localization: ^3.0.0
  enum_to_string: ^1.0.14
  file_picker: ^3.0.0
  flushbar: ^1.9.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.0.0-nullsafety.1
  flutter_secure_storage: ^4.0.0
  flutter_uploader: ^1.2.0
  http: ^0.13.0
  image_picker: ^0.7.2
  intl: ^0.17.0
  moor: ^4.1.0
  photo_manager: ^0.6.0
  photo_view: ^0.10.3
  progress_dialog: ^1.2.0
  provider: ^5.0.0
  share: ^2.0.0
  shared_preferences: ^2.0.3
  sqlite3_flutter_libs: ^0.4.0+1
  url_launcher: ^6.0.2
  video_player: ^2.0.0

dev_dependencies:
  build_runner: ^1.11.0
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.4
  moor_generator: ^4.1.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_ios: "assets/app_logo_ios.png"
  image_path_android: "assets/app_logo.png"
  adaptive_icon_background: "assets/app_logo_bg.png"
  adaptive_icon_foreground: "assets/app_logo_fg.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/themes.json
    - assets/translations/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
