name: photoprism
description: An app for photoprism.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_uploader: ^1.2.0
  image_picker: ^0.6.1
  http: ^0.12.0
  easy_localization: ^2.3.3
  shared_preferences: ^0.5.6
  photo_view: ^0.10.3
  cached_network_image: ^2.1.1
  flutter_cache_manager: ^2.1.1
  provider: ^4.3.3
  drag_select_grid_view: ^0.3.1
  progress_dialog: ^1.2.0
  file_picker: ^2.1.6
  background_fetch: ^0.6.0
  intl: ^0.16.0
  flushbar: ^1.9.1
  esys_flutter_share: ^1.0.2
  crypto: ^2.1.3
  flutter_secure_storage: ^3.3.5
  photo_manager: ^0.6.0
  device_info: ^1.0.0
  video_player: '>=0.10.11+2 <2.0.0'
  url_launcher: ^5.7.10
  moor: ^3.4.0
  sqlite3_flutter_libs: ^0.3.0
  enum_to_string: ^1.0.14
  draggable_scrollbar:
    git:
      url: git://github.com/thielepaul/flutter-draggable-scrollbar.git

dev_dependencies:
  moor_generator: ^3.4.1
  build_runner: ^1.11.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.1"
  mockito: ^4.1.4

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_ios: "assets/app_logo_ios.png"
  image_path_android: "assets/app_logo.png"
  adaptive_icon_background: "assets/app_logo_bg.png"
  adaptive_icon_foreground: "assets/app_logo_fg.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/themes.json
    - assets/translations/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
