name: Pull Request CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.12.13"
          channel: "stable"
      - run: flutter format --dry-run --set-exit-if-changed lib
      - run: flutter analyze
      - run: flutter pub get
      - run: flutter test --coverage
      - run: flutter build apk --profile --flavor dev --no-shrink
      - uses: actions/upload-artifact@v1
        with:
          name: photoprism-apk
          path: build/app/outputs/apk/dev/profile/
